name: Build & Test

on:
  #  push:
  #    branches: [master]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install # yarn 사용시 yarn install --frozen-lockfile

      - name: Build & Test
        run: |
          npm run ci:test
          npm run ci:deploy-before

      # - uses: codecov/codecov-action@v1
      #   with:
      #     directory: ./coverage

      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-runners-access-token-github_token
          publish_dir: "./docs"