name: Release deploy

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

jobs:

  # 릴리즈 npm
  release-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 소스 가져오기
      - uses: actions/setup-node@v1 # 노드 설정하기
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      # 모듈 설치
      - name: Install dependencies
        run: npm ci # yarn 사용시 yarn install --frozen-lockfile

      # 테스트
      - name: Test
        run: npm run ci:test
      
      # 빌드
      - name: Build
        run: npm run ci:build

      # 퍼블리시 npm
      - name: NPM publish
        run: npm publish ./dist/jd-modal
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

  # 릴리즈 doc
  release-doc:
    needs: release-ready
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/doc')
    steps:
      - uses: actions/checkout@v2 # 소스 가져오기
      - uses: actions/setup-node@v1 # 노드 설정하기
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          
      # 모듈 설치
      - name: Install dependencies
        run: npm ci # yarn 사용시 yarn install --frozen-lockfile

      # doc dist
      - name: Doc Generate
        run: |
          npm run page:clear
          npm run page:expose

      # gh-pages
      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-runners-access-token-github_token
          publish_dir: "./docs"

