name: Release deploy

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

jobs:
  release-ready:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci # yarn 사용시 yarn install --frozen-lockfile

      - name: Build and Test
        run: |
          npm run ci:test
          npm run ci:deploy-before

  release-n-publish:
    needs: release-ready
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: NPM publish
        run: npm publish ./dist/jd-modal
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-runners-access-token-github_token
          publish_dir: "./docs"

  release-only-doc:
    needs: release-ready
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/doc')
    steps:
      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-runners-access-token-github_token
          publish_dir: "./docs"
